# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'TestProject' do
  use_frameworks!
  
  pod 'LookinServer', :configurations => ['Debug']
  

end
