# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

workspace '../ZSWorkspace.xcworkspace'
target 'ZSFramework' do
  use_frameworks! # 使用动态库
  pod "AFNetworking"
end

target 'ZSApp' do
  project '../ZSApp/ZSApp.xcodeproj'
  use_frameworks! # 使用动态库
  #pod 'AFNetworking'
  
end
